### PR TITLE
update 50 packages

### PR DESCRIPTION
**Pull request by zkamvar**
I've run the package update manually because the automated workflow was having trouble after the release of {renv} 1.0.0.

This brings in updates to 50 packages. Please wait for the output to run and then check for any new errors, warnings or surprising output changes.

I ran the following commands to update the cache with {renv} 1.0.2

```r
sandpaper::manage_deps()
sandpaper::update_cache()
```

```
- 50 packages have updates available.

# BioCsoft -------------------------------------------------------------------
- affy              [1.78.0 -> 1.78.2]
- clusterProfiler   [4.8.1 -> 4.8.3]
- DelayedArray      [0.26.6 -> 0.26.7]
- enrichplot        [1.20.0 -> 1.20.1]
- GenomeInfoDb      [1.36.1 -> 1.36.2]
- ggtree            [3.8.0 -> 3.8.2]
- GOSemSim          [2.26.0 -> 2.26.1]
- MatrixGenerics    [1.12.2 -> 1.12.3]
- S4Arrays          [1.0.4 -> 1.0.6]
- treeio            [1.24.1 -> 1.24.3]

# CRAN -----------------------------------------------------------------------
- aplot             [0.1.10 -> 0.2.0]
- askpass           [1.1 -> 1.2.0]
- BiocManager       [1.30.21 -> 1.30.22]
- boot              [1.3-28 -> 1.3-28.1]
- bslib             [repo: RSPM -> CRAN; ver: 0.5.0 -> 0.5.1]
- cpp11             [repo: RSPM -> CRAN; ver: 0.4.4 -> 0.4.6]
- curl              [repo: RSPM -> CRAN; ver: 5.0.1 -> 5.0.2]
- dplyr             [1.1.2 -> 1.1.3]
- DT                [0.28 -> 0.29]
- fastmatch         [1.1-3 -> 1.1-4]
- fontawesome       [0.5.1 -> 0.5.2]
- foreign           [0.8-82 -> 0.8-84]
- fs                [1.6.2 -> 1.6.3]
- ggfun             [0.1.1 -> 0.1.2]
- ggplot2           [3.4.2 -> 3.4.3]
- ggplotify         [0.1.1 -> 0.1.2]
- gtable            [0.3.3 -> 0.3.4]
- htmltools         [repo: RSPM -> CRAN; ver: 0.5.5 -> 0.5.6]
- httr              [1.4.6 -> 1.4.7]
- igraph            [1.5.0 -> 1.5.1]
- labeling          [0.4.2 -> 0.4.3]
- Matrix            [1.5-4.1 -> 1.6-1]
- mgcv              [1.8-42 -> 1.9-0]
- mvtnorm           [1.2-2 -> 1.2-3]
- nlme              [3.1-162 -> 3.1-163]
- openssl           [2.0.6 -> 2.1.0]
- patchwork         [1.1.2 -> 1.1.3]
- promises          [repo: RSPM -> CRAN; ver: 1.2.0.1 -> 1.2.1]
- purrr             [repo: RSPM -> CRAN; ver: 1.0.1 -> 1.0.2]
- RcppArmadillo     [0.12.4.1.0 -> 0.12.6.3.0]
- renv              [0.17.3 -> 1.0.2]
- rmarkdown         [repo: RSPM -> CRAN; ver: 2.23 -> 2.24]
- sass              [0.4.6 -> 0.4.7]
- shiny             [1.7.4.1 -> 1.7.5]
- survival          [3.5-5 -> 3.5-7]
- tidytree          [0.4.2 -> 0.4.5]
- tinytex           [0.45 -> 0.46]
- viridis           [0.6.3 -> 0.6.4]
- xfun              [0.39 -> 0.40]
- yulab.utils       [0.0.6 -> 0.0.9]
```

### CODE REVIEW

**Comment by csoneson** [comment]
Thanks @zkamvar! Just wanted to be sure - should the `config.yaml` and `renv.lock` files disappear (the figures may be ok, perhaps I should actually render them in another way)? I see the same happened in the other bioc lessons.

**Comment by zkamvar** [comment]
> Just wanted to be sure - should the `config.yaml` and `renv.lock` files disappear (the figures may be ok, perhaps I should actually render them in another way)? I see the same happened in the other bioc lessons.

This is a weird thing that happens only in the pull request previews and I'm not sure why, but these actions are ultimately harmless as they always end up appearing in the correct places in the end.

**Comment by csoneson** [comment]
Ok, thanks!

**Comment by zkamvar** [comment]
I think for the images, it's a bit confusing as to why they would disappear like that and I'm running the lesson locally now to see if that's a real problem or if that's an artefact of the PR process. One thing I would recommend is to use a package like {namer} to name the chunks: https://jumpingrivers.github.io/namer/ and then continue to name them as you go along.

**Comment by zkamvar** [comment]
It looks like they appear locally, so it's likely a bug in the PR preview mechanism.

**Comment by csoneson** [comment]
👍🏻 And yes, totally agree about the naming, this was an oversight from my side - I'll update the chunks.

**Pull request merged**
